---
- hosts: sample-instance-*
  become: yes
  tasks:
    - name: Copy file with owner, group, permissions
      ansible.builtin.fetch:
        src: /etc/foo
        dest: /etc/foo
        flat: yes
        owner: root
        group: root
        mode: '0644'